# ===================================================================
# Spring Boot configuration
# ===================================================================
spring:
  application:
    name: example
  h2:
   console:
     enabled: true
     path: /h2
  jpa:
    generate-ddl: true
    hibernate:
        ddl-auto: update
    show-sql: false

## ===================================================================
## Liquibase Properties
## ===================================================================
#liquibase: 
#  changeLogFile: src/main/resources/db/master.yml
#  url: jdbc:h2:file:./target/liquibase_test;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
#  username: admin
#  password: admin
#  driver: org.h2.Driver
#  enabled: false
#
#  referenceUrl: hibernate:spring:com.base.example.liquibase.model?dialect=org.hibernate.dialect.H2Dialect
